"""Domain models for the Plantation Model service.

This module re-exports all domain models from fp-common for backwards compatibility.
Models have been moved to fp-common to enable sharing across services and MCP servers.

Import patterns that continue to work:
    from plantation_model.domain.models import Farmer, Factory, Region
    from plantation_model.domain.models import FarmScale, GradingModel
"""

# Re-export all models from fp-common
from fp_common.models import (
    GPS,
    Agronomic,
    AltitudeBand,
    AltitudeBandLabel,
    CollectionPoint,
    CollectionPointCapacity,
    CollectionPointCreate,
    CollectionPointUpdate,
    ConditionalReject,
    ContactInfo,
    Factory,
    FactoryCreate,
    FactoryUpdate,
    Farmer,
    FarmerCreate,
    FarmerPerformance,
    FarmerUpdate,
    FarmScale,
    FlushCalendar,
    FlushPeriod,
    Geography,
    GeoLocation,
    GradeRules,
    GradingAttribute,
    GradingModel,
    GradingType,
    HistoricalMetrics,
    InteractionPreference,
    NotificationChannel,
    OperatingHours,
    PaymentPolicy,
    PaymentPolicyType,
    PreferredChannel,
    PreferredLanguage,
    QualityThresholds,
    Region,
    RegionalWeather,
    RegionCreate,
    RegionUpdate,
    TodayMetrics,
    TrendDirection,
    WeatherConfig,
    WeatherObservation,
)

__all__ = [
    "GPS",
    "Agronomic",
    "AltitudeBand",
    "AltitudeBandLabel",
    "CollectionPoint",
    "CollectionPointCapacity",
    "CollectionPointCreate",
    "CollectionPointUpdate",
    "ConditionalReject",
    "ContactInfo",
    "Factory",
    "FactoryCreate",
    "FactoryUpdate",
    "FarmScale",
    "Farmer",
    "FarmerCreate",
    "FarmerPerformance",
    "FarmerUpdate",
    "FlushCalendar",
    "FlushPeriod",
    "GeoLocation",
    "Geography",
    "GradeRules",
    "GradingAttribute",
    "GradingModel",
    "GradingType",
    "HistoricalMetrics",
    "InteractionPreference",
    "NotificationChannel",
    "OperatingHours",
    "PaymentPolicy",
    "PaymentPolicyType",
    "PreferredChannel",
    "PreferredLanguage",
    "QualityThresholds",
    "Region",
    "RegionCreate",
    "RegionUpdate",
    "RegionalWeather",
    "TodayMetrics",
    "TrendDirection",
    "WeatherConfig",
    "WeatherObservation",
]
