# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fp_proto.mcp.v1 import mcp_tool_pb2 as mcp_dot_v1_dot_mcp__tool__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp/v1/mcp_tool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class McpToolServiceStub(object):
    """McpToolService provides tool invocation for AI agents
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTools = channel.unary_unary(
                '/farmer_power.mcp.v1.McpToolService/ListTools',
                request_serializer=mcp_dot_v1_dot_mcp__tool__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__tool__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/farmer_power.mcp.v1.McpToolService/CallTool',
                request_serializer=mcp_dot_v1_dot_mcp__tool__pb2.ToolCallRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__tool__pb2.ToolCallResponse.FromString,
                _registered_method=True)


class McpToolServiceServicer(object):
    """McpToolService provides tool invocation for AI agents
    """

    def ListTools(self, request, context):
        """List available tools with their schemas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Invoke a specific tool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_McpToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=mcp_dot_v1_dot_mcp__tool__pb2.ListToolsRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__tool__pb2.ListToolsResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=mcp_dot_v1_dot_mcp__tool__pb2.ToolCallRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__tool__pb2.ToolCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'farmer_power.mcp.v1.McpToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('farmer_power.mcp.v1.McpToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class McpToolService(object):
    """McpToolService provides tool invocation for AI agents
    """

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.mcp.v1.McpToolService/ListTools',
            mcp_dot_v1_dot_mcp__tool__pb2.ListToolsRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__tool__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.mcp.v1.McpToolService/CallTool',
            mcp_dot_v1_dot_mcp__tool__pb2.ToolCallRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__tool__pb2.ToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
