# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp/v1/mcp_tool.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mcp/v1/mcp_tool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15mcp/v1/mcp_tool.proto\x12\x13\x66\x61rmer_power.mcp.v1\"$\n\x10ListToolsRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"G\n\x11ListToolsResponse\x12\x32\n\x05tools\x18\x01 \x03(\x0b\x32#.farmer_power.mcp.v1.ToolDefinition\"`\n\x0eToolDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x19\n\x11input_schema_json\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\"g\n\x0fToolCallRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02 \x01(\t\x12\x10\n\x08trace_id\x18\x03 \x01(\t\x12\x17\n\x0f\x63\x61ller_agent_id\x18\x04 \x01(\t\"\x83\x01\n\x10ToolCallResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\x32\n\nerror_code\x18\x03 \x01(\x0e\x32\x1e.farmer_power.mcp.v1.ErrorCode\x12\x15\n\rerror_message\x18\x04 \x01(\t*\xab\x01\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12 \n\x1c\x45RROR_CODE_INVALID_ARGUMENTS\x10\x01\x12\"\n\x1e\x45RROR_CODE_SERVICE_UNAVAILABLE\x10\x02\x12\x1d\n\x19\x45RROR_CODE_TOOL_NOT_FOUND\x10\x03\x12\x1d\n\x19\x45RROR_CODE_INTERNAL_ERROR\x10\x04\x32\xc5\x01\n\x0eMcpToolService\x12Z\n\tListTools\x12%.farmer_power.mcp.v1.ListToolsRequest\x1a&.farmer_power.mcp.v1.ListToolsResponse\x12W\n\x08\x43\x61llTool\x12$.farmer_power.mcp.v1.ToolCallRequest\x1a%.farmer_power.mcp.v1.ToolCallResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp.v1.mcp_tool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCODE']._serialized_start=495
  _globals['_ERRORCODE']._serialized_end=666
  _globals['_LISTTOOLSREQUEST']._serialized_start=46
  _globals['_LISTTOOLSREQUEST']._serialized_end=82
  _globals['_LISTTOOLSRESPONSE']._serialized_start=84
  _globals['_LISTTOOLSRESPONSE']._serialized_end=155
  _globals['_TOOLDEFINITION']._serialized_start=157
  _globals['_TOOLDEFINITION']._serialized_end=253
  _globals['_TOOLCALLREQUEST']._serialized_start=255
  _globals['_TOOLCALLREQUEST']._serialized_end=358
  _globals['_TOOLCALLRESPONSE']._serialized_start=361
  _globals['_TOOLCALLRESPONSE']._serialized_end=492
  _globals['_MCPTOOLSERVICE']._serialized_start=669
  _globals['_MCPTOOLSERVICE']._serialized_end=866
# @@protoc_insertion_point(module_scope)
