# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fp_proto.plantation.v1 import plantation_pb2 as plantation_dot_v1_dot_plantation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plantation/v1/plantation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlantationServiceStub(object):
    """Note: Health checking uses standard grpc.health.v1.Health (grpc-health-checking package)
    No custom HealthService defined here to avoid duplication.

    ============================================================================
    Plantation Service - Core Operations
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRegion = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetRegion',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetRegionRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Region.FromString,
                _registered_method=True)
        self.ListRegions = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/ListRegions',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.ListRegionsRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.ListRegionsResponse.FromString,
                _registered_method=True)
        self.CreateRegion = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/CreateRegion',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.CreateRegionRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Region.FromString,
                _registered_method=True)
        self.UpdateRegion = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/UpdateRegion',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.UpdateRegionRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Region.FromString,
                _registered_method=True)
        self.GetRegionWeather = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetRegionWeather',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetRegionWeatherRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.GetRegionWeatherResponse.FromString,
                _registered_method=True)
        self.GetCurrentFlush = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetCurrentFlush',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetCurrentFlushRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.GetCurrentFlushResponse.FromString,
                _registered_method=True)
        self.GetFactory = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetFactory',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetFactoryRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Factory.FromString,
                _registered_method=True)
        self.ListFactories = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/ListFactories',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.ListFactoriesRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.ListFactoriesResponse.FromString,
                _registered_method=True)
        self.CreateFactory = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/CreateFactory',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.CreateFactoryRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Factory.FromString,
                _registered_method=True)
        self.UpdateFactory = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/UpdateFactory',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.UpdateFactoryRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Factory.FromString,
                _registered_method=True)
        self.DeleteFactory = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/DeleteFactory',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.DeleteFactoryRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.DeleteFactoryResponse.FromString,
                _registered_method=True)
        self.GetFarmer = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetFarmer',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetFarmerRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Farmer.FromString,
                _registered_method=True)
        self.GetFarmerByPhone = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetFarmerByPhone',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetFarmerByPhoneRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Farmer.FromString,
                _registered_method=True)
        self.ListFarmers = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/ListFarmers',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.ListFarmersRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.ListFarmersResponse.FromString,
                _registered_method=True)
        self.CreateFarmer = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/CreateFarmer',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.CreateFarmerRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Farmer.FromString,
                _registered_method=True)
        self.UpdateFarmer = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/UpdateFarmer',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.UpdateFarmerRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.Farmer.FromString,
                _registered_method=True)
        self.GetCollectionPoint = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetCollectionPoint',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetCollectionPointRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
                _registered_method=True)
        self.ListCollectionPoints = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/ListCollectionPoints',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.ListCollectionPointsRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.ListCollectionPointsResponse.FromString,
                _registered_method=True)
        self.CreateCollectionPoint = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/CreateCollectionPoint',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.CreateCollectionPointRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
                _registered_method=True)
        self.UpdateCollectionPoint = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/UpdateCollectionPoint',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.UpdateCollectionPointRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
                _registered_method=True)
        self.DeleteCollectionPoint = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/DeleteCollectionPoint',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.DeleteCollectionPointRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.DeleteCollectionPointResponse.FromString,
                _registered_method=True)
        self.GetPerformanceSummary = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetPerformanceSummary',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetPerformanceSummaryRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.PerformanceSummary.FromString,
                _registered_method=True)
        self.CreateGradingModel = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/CreateGradingModel',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.CreateGradingModelRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.GradingModel.FromString,
                _registered_method=True)
        self.GetGradingModel = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetGradingModel',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetGradingModelRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.GradingModel.FromString,
                _registered_method=True)
        self.GetFactoryGradingModel = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetFactoryGradingModel',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetFactoryGradingModelRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.GradingModel.FromString,
                _registered_method=True)
        self.AssignGradingModelToFactory = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/AssignGradingModelToFactory',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.AssignGradingModelToFactoryRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.GradingModel.FromString,
                _registered_method=True)
        self.GetFarmerSummary = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetFarmerSummary',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetFarmerSummaryRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.FarmerSummary.FromString,
                _registered_method=True)
        self.UpdateCommunicationPreferences = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/UpdateCommunicationPreferences',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.UpdateCommunicationPreferencesRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.UpdateCommunicationPreferencesResponse.FromString,
                _registered_method=True)
        self.AssignFarmerToCollectionPoint = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/AssignFarmerToCollectionPoint',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.AssignFarmerRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
                _registered_method=True)
        self.UnassignFarmerFromCollectionPoint = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/UnassignFarmerFromCollectionPoint',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.UnassignFarmerRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
                _registered_method=True)
        self.GetCollectionPointsForFarmer = channel.unary_unary(
                '/farmer_power.plantation.v1.PlantationService/GetCollectionPointsForFarmer',
                request_serializer=plantation_dot_v1_dot_plantation__pb2.GetCollectionPointsForFarmerRequest.SerializeToString,
                response_deserializer=plantation_dot_v1_dot_plantation__pb2.ListCollectionPointsResponse.FromString,
                _registered_method=True)


class PlantationServiceServicer(object):
    """Note: Health checking uses standard grpc.health.v1.Health (grpc-health-checking package)
    No custom HealthService defined here to avoid duplication.

    ============================================================================
    Plantation Service - Core Operations
    ============================================================================

    """

    def GetRegion(self, request, context):
        """Region operations (Story 1.8)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRegions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegionWeather(self, request, context):
        """Regional Weather operations (Story 1.8)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentFlush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFactory(self, request, context):
        """Factory operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFactories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFactory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFactory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFactory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFarmer(self, request, context):
        """Farmer operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFarmerByPhone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFarmers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFarmer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFarmer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionPoint(self, request, context):
        """Collection Point operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollectionPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollectionPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCollectionPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollectionPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPerformanceSummary(self, request, context):
        """Performance summary operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGradingModel(self, request, context):
        """Grading Model operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGradingModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFactoryGradingModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignGradingModelToFactory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFarmerSummary(self, request, context):
        """Farmer Performance operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCommunicationPreferences(self, request, context):
        """Communication Preferences operations (Story 1.5)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignFarmerToCollectionPoint(self, request, context):
        """Farmer-CollectionPoint assignment operations (Story 9.5a)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnassignFarmerFromCollectionPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionPointsForFarmer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlantationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegion,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetRegionRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Region.SerializeToString,
            ),
            'ListRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRegions,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.ListRegionsRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.ListRegionsResponse.SerializeToString,
            ),
            'CreateRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRegion,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.CreateRegionRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Region.SerializeToString,
            ),
            'UpdateRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRegion,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.UpdateRegionRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Region.SerializeToString,
            ),
            'GetRegionWeather': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegionWeather,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetRegionWeatherRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.GetRegionWeatherResponse.SerializeToString,
            ),
            'GetCurrentFlush': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentFlush,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetCurrentFlushRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.GetCurrentFlushResponse.SerializeToString,
            ),
            'GetFactory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFactory,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetFactoryRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Factory.SerializeToString,
            ),
            'ListFactories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFactories,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.ListFactoriesRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.ListFactoriesResponse.SerializeToString,
            ),
            'CreateFactory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFactory,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.CreateFactoryRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Factory.SerializeToString,
            ),
            'UpdateFactory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFactory,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.UpdateFactoryRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Factory.SerializeToString,
            ),
            'DeleteFactory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFactory,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.DeleteFactoryRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.DeleteFactoryResponse.SerializeToString,
            ),
            'GetFarmer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFarmer,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetFarmerRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Farmer.SerializeToString,
            ),
            'GetFarmerByPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFarmerByPhone,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetFarmerByPhoneRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Farmer.SerializeToString,
            ),
            'ListFarmers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFarmers,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.ListFarmersRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.ListFarmersResponse.SerializeToString,
            ),
            'CreateFarmer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFarmer,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.CreateFarmerRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Farmer.SerializeToString,
            ),
            'UpdateFarmer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFarmer,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.UpdateFarmerRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.Farmer.SerializeToString,
            ),
            'GetCollectionPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionPoint,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetCollectionPointRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.SerializeToString,
            ),
            'ListCollectionPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollectionPoints,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.ListCollectionPointsRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.ListCollectionPointsResponse.SerializeToString,
            ),
            'CreateCollectionPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollectionPoint,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.CreateCollectionPointRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.SerializeToString,
            ),
            'UpdateCollectionPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCollectionPoint,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.UpdateCollectionPointRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.SerializeToString,
            ),
            'DeleteCollectionPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollectionPoint,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.DeleteCollectionPointRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.DeleteCollectionPointResponse.SerializeToString,
            ),
            'GetPerformanceSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPerformanceSummary,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetPerformanceSummaryRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.PerformanceSummary.SerializeToString,
            ),
            'CreateGradingModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGradingModel,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.CreateGradingModelRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.GradingModel.SerializeToString,
            ),
            'GetGradingModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGradingModel,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetGradingModelRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.GradingModel.SerializeToString,
            ),
            'GetFactoryGradingModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFactoryGradingModel,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetFactoryGradingModelRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.GradingModel.SerializeToString,
            ),
            'AssignGradingModelToFactory': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignGradingModelToFactory,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.AssignGradingModelToFactoryRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.GradingModel.SerializeToString,
            ),
            'GetFarmerSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFarmerSummary,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetFarmerSummaryRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.FarmerSummary.SerializeToString,
            ),
            'UpdateCommunicationPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCommunicationPreferences,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.UpdateCommunicationPreferencesRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.UpdateCommunicationPreferencesResponse.SerializeToString,
            ),
            'AssignFarmerToCollectionPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignFarmerToCollectionPoint,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.AssignFarmerRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.SerializeToString,
            ),
            'UnassignFarmerFromCollectionPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.UnassignFarmerFromCollectionPoint,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.UnassignFarmerRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.CollectionPoint.SerializeToString,
            ),
            'GetCollectionPointsForFarmer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionPointsForFarmer,
                    request_deserializer=plantation_dot_v1_dot_plantation__pb2.GetCollectionPointsForFarmerRequest.FromString,
                    response_serializer=plantation_dot_v1_dot_plantation__pb2.ListCollectionPointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'farmer_power.plantation.v1.PlantationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('farmer_power.plantation.v1.PlantationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlantationService(object):
    """Note: Health checking uses standard grpc.health.v1.Health (grpc-health-checking package)
    No custom HealthService defined here to avoid duplication.

    ============================================================================
    Plantation Service - Core Operations
    ============================================================================

    """

    @staticmethod
    def GetRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetRegion',
            plantation_dot_v1_dot_plantation__pb2.GetRegionRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Region.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/ListRegions',
            plantation_dot_v1_dot_plantation__pb2.ListRegionsRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.ListRegionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/CreateRegion',
            plantation_dot_v1_dot_plantation__pb2.CreateRegionRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Region.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/UpdateRegion',
            plantation_dot_v1_dot_plantation__pb2.UpdateRegionRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Region.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegionWeather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetRegionWeather',
            plantation_dot_v1_dot_plantation__pb2.GetRegionWeatherRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.GetRegionWeatherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentFlush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetCurrentFlush',
            plantation_dot_v1_dot_plantation__pb2.GetCurrentFlushRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.GetCurrentFlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFactory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetFactory',
            plantation_dot_v1_dot_plantation__pb2.GetFactoryRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Factory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFactories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/ListFactories',
            plantation_dot_v1_dot_plantation__pb2.ListFactoriesRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.ListFactoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFactory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/CreateFactory',
            plantation_dot_v1_dot_plantation__pb2.CreateFactoryRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Factory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFactory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/UpdateFactory',
            plantation_dot_v1_dot_plantation__pb2.UpdateFactoryRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Factory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFactory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/DeleteFactory',
            plantation_dot_v1_dot_plantation__pb2.DeleteFactoryRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.DeleteFactoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFarmer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetFarmer',
            plantation_dot_v1_dot_plantation__pb2.GetFarmerRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Farmer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFarmerByPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetFarmerByPhone',
            plantation_dot_v1_dot_plantation__pb2.GetFarmerByPhoneRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Farmer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFarmers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/ListFarmers',
            plantation_dot_v1_dot_plantation__pb2.ListFarmersRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.ListFarmersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFarmer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/CreateFarmer',
            plantation_dot_v1_dot_plantation__pb2.CreateFarmerRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Farmer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFarmer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/UpdateFarmer',
            plantation_dot_v1_dot_plantation__pb2.UpdateFarmerRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.Farmer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetCollectionPoint',
            plantation_dot_v1_dot_plantation__pb2.GetCollectionPointRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollectionPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/ListCollectionPoints',
            plantation_dot_v1_dot_plantation__pb2.ListCollectionPointsRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.ListCollectionPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollectionPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/CreateCollectionPoint',
            plantation_dot_v1_dot_plantation__pb2.CreateCollectionPointRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCollectionPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/UpdateCollectionPoint',
            plantation_dot_v1_dot_plantation__pb2.UpdateCollectionPointRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollectionPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/DeleteCollectionPoint',
            plantation_dot_v1_dot_plantation__pb2.DeleteCollectionPointRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.DeleteCollectionPointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPerformanceSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetPerformanceSummary',
            plantation_dot_v1_dot_plantation__pb2.GetPerformanceSummaryRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.PerformanceSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGradingModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/CreateGradingModel',
            plantation_dot_v1_dot_plantation__pb2.CreateGradingModelRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.GradingModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGradingModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetGradingModel',
            plantation_dot_v1_dot_plantation__pb2.GetGradingModelRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.GradingModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFactoryGradingModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetFactoryGradingModel',
            plantation_dot_v1_dot_plantation__pb2.GetFactoryGradingModelRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.GradingModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignGradingModelToFactory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/AssignGradingModelToFactory',
            plantation_dot_v1_dot_plantation__pb2.AssignGradingModelToFactoryRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.GradingModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFarmerSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetFarmerSummary',
            plantation_dot_v1_dot_plantation__pb2.GetFarmerSummaryRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.FarmerSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCommunicationPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/UpdateCommunicationPreferences',
            plantation_dot_v1_dot_plantation__pb2.UpdateCommunicationPreferencesRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.UpdateCommunicationPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignFarmerToCollectionPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/AssignFarmerToCollectionPoint',
            plantation_dot_v1_dot_plantation__pb2.AssignFarmerRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnassignFarmerFromCollectionPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/UnassignFarmerFromCollectionPoint',
            plantation_dot_v1_dot_plantation__pb2.UnassignFarmerRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.CollectionPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionPointsForFarmer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.plantation.v1.PlantationService/GetCollectionPointsForFarmer',
            plantation_dot_v1_dot_plantation__pb2.GetCollectionPointsForFarmerRequest.SerializeToString,
            plantation_dot_v1_dot_plantation__pb2.ListCollectionPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
