# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: poc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'poc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpoc.proto\x12\x06poc.v1\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\".\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0f\n\x07service\x18\x02 \x01(\t2@\n\x0b\x45\x63hoService\x12\x31\n\x04\x45\x63ho\x12\x13.poc.v1.EchoRequest\x1a\x14.poc.v1.EchoResponse2C\n\x11\x43\x61lculatorService\x12.\n\x03\x41\x64\x64\x12\x12.poc.v1.AddRequest\x1a\x13.poc.v1.AddResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'poc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=21
  _globals['_ECHOREQUEST']._serialized_end=51
  _globals['_ECHORESPONSE']._serialized_start=53
  _globals['_ECHORESPONSE']._serialized_end=101
  _globals['_ADDREQUEST']._serialized_start=103
  _globals['_ADDREQUEST']._serialized_end=137
  _globals['_ADDRESPONSE']._serialized_start=139
  _globals['_ADDRESPONSE']._serialized_end=185
  _globals['_ECHOSERVICE']._serialized_start=187
  _globals['_ECHOSERVICE']._serialized_end=251
  _globals['_CALCULATORSERVICE']._serialized_start=253
  _globals['_CALCULATORSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
