# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fp_proto.ai_model.v1 import ai_model_pb2 as ai__model_dot_v1_dot_ai__model__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_model/v1/ai_model_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiModelServiceStub(object):
    """AiModelService provides LLM-based extraction capabilities
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Extract = channel.unary_unary(
                '/farmer_power.ai_model.v1.AiModelService/Extract',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractionRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/farmer_power.ai_model.v1.AiModelService/HealthCheck',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AiModelServiceServicer(object):
    """AiModelService provides LLM-based extraction capabilities
    """

    def Extract(self, request, context):
        """Extract structured data from raw content using LLM
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for service readiness
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Extract': grpc.unary_unary_rpc_method_handler(
                    servicer.Extract,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractionRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'farmer_power.ai_model.v1.AiModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('farmer_power.ai_model.v1.AiModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiModelService(object):
    """AiModelService provides LLM-based extraction capabilities
    """

    @staticmethod
    def Extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.AiModelService/Extract',
            ai__model_dot_v1_dot_ai__model__pb2.ExtractionRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.ExtractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.AiModelService/HealthCheck',
            ai__model_dot_v1_dot_ai__model__pb2.HealthCheckRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RAGDocumentServiceStub(object):
    """============================================
    RAG Document Service (Story 0.75.10)
    Manages RAG knowledge documents with versioning
    ============================================

    RAGDocumentService provides RAG document management capabilities
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/CreateDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.CreateDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.CreateDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/GetDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
                _registered_method=True)
        self.UpdateDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/UpdateDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.UpdateDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/DeleteDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/ListDocuments',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.SearchDocuments = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/SearchDocuments',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.SearchDocumentsRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.SearchDocumentsResponse.FromString,
                _registered_method=True)
        self.StageDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/StageDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.StageDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
                _registered_method=True)
        self.ActivateDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/ActivateDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.ActivateDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
                _registered_method=True)
        self.ArchiveDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/ArchiveDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.ArchiveDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
                _registered_method=True)
        self.RollbackDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/RollbackDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.RollbackDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
                _registered_method=True)
        self.ExtractDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/ExtractDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractDocumentResponse.FromString,
                _registered_method=True)
        self.GetExtractionJob = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/GetExtractionJob',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.GetExtractionJobRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractionJobResponse.FromString,
                _registered_method=True)
        self.StreamExtractionProgress = channel.unary_stream(
                '/farmer_power.ai_model.v1.RAGDocumentService/StreamExtractionProgress',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.StreamExtractionProgressRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractionProgressEvent.FromString,
                _registered_method=True)
        self.ChunkDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/ChunkDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.ChunkDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ChunkDocumentResponse.FromString,
                _registered_method=True)
        self.ListChunks = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/ListChunks',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.ListChunksRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ListChunksResponse.FromString,
                _registered_method=True)
        self.GetChunk = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/GetChunk',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.GetChunkRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.RagChunk.FromString,
                _registered_method=True)
        self.DeleteChunks = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/DeleteChunks',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.DeleteChunksRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.DeleteChunksResponse.FromString,
                _registered_method=True)
        self.VectorizeDocument = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/VectorizeDocument',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.VectorizeDocumentRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.VectorizeDocumentResponse.FromString,
                _registered_method=True)
        self.GetVectorizationJob = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/GetVectorizationJob',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.GetVectorizationJobRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.VectorizationJobResponse.FromString,
                _registered_method=True)
        self.QueryKnowledge = channel.unary_unary(
                '/farmer_power.ai_model.v1.RAGDocumentService/QueryKnowledge',
                request_serializer=ai__model_dot_v1_dot_ai__model__pb2.QueryKnowledgeRequest.SerializeToString,
                response_deserializer=ai__model_dot_v1_dot_ai__model__pb2.QueryKnowledgeResponse.FromString,
                _registered_method=True)


class RAGDocumentServiceServicer(object):
    """============================================
    RAG Document Service (Story 0.75.10)
    Manages RAG knowledge documents with versioning
    ============================================

    RAGDocumentService provides RAG document management capabilities
    """

    def CreateDocument(self, request, context):
        """CRUD Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """List & Search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StageDocument(self, request, context):
        """Lifecycle Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractDocument(self, request, context):
        """Extraction Operations (Story 0.75.10b)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExtractionJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExtractionProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChunkDocument(self, request, context):
        """Chunking Operations (Story 0.75.10d)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorizeDocument(self, request, context):
        """Vectorization Operations (Story 0.75.13b)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectorizationJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryKnowledge(self, request, context):
        """Query Operations (Story 0.75.23)
        Query knowledge base with natural language for RAG retrieval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGDocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.CreateDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.CreateDocumentResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.GetDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.SerializeToString,
            ),
            'UpdateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.UpdateDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ListDocumentsRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.SearchDocumentsRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.SearchDocumentsResponse.SerializeToString,
            ),
            'StageDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.StageDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.StageDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.SerializeToString,
            ),
            'ActivateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ActivateDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.SerializeToString,
            ),
            'ArchiveDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ArchiveDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.SerializeToString,
            ),
            'RollbackDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.RollbackDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.SerializeToString,
            ),
            'ExtractDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractDocumentResponse.SerializeToString,
            ),
            'GetExtractionJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExtractionJob,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.GetExtractionJobRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractionJobResponse.SerializeToString,
            ),
            'StreamExtractionProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamExtractionProgress,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.StreamExtractionProgressRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.ExtractionProgressEvent.SerializeToString,
            ),
            'ChunkDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ChunkDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ChunkDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.ChunkDocumentResponse.SerializeToString,
            ),
            'ListChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChunks,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.ListChunksRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.ListChunksResponse.SerializeToString,
            ),
            'GetChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChunk,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.GetChunkRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.RagChunk.SerializeToString,
            ),
            'DeleteChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChunks,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.DeleteChunksRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.DeleteChunksResponse.SerializeToString,
            ),
            'VectorizeDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorizeDocument,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.VectorizeDocumentRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.VectorizeDocumentResponse.SerializeToString,
            ),
            'GetVectorizationJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectorizationJob,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.GetVectorizationJobRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.VectorizationJobResponse.SerializeToString,
            ),
            'QueryKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryKnowledge,
                    request_deserializer=ai__model_dot_v1_dot_ai__model__pb2.QueryKnowledgeRequest.FromString,
                    response_serializer=ai__model_dot_v1_dot_ai__model__pb2.QueryKnowledgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'farmer_power.ai_model.v1.RAGDocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('farmer_power.ai_model.v1.RAGDocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGDocumentService(object):
    """============================================
    RAG Document Service (Story 0.75.10)
    Manages RAG knowledge documents with versioning
    ============================================

    RAGDocumentService provides RAG document management capabilities
    """

    @staticmethod
    def CreateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/CreateDocument',
            ai__model_dot_v1_dot_ai__model__pb2.CreateDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.CreateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/GetDocument',
            ai__model_dot_v1_dot_ai__model__pb2.GetDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/UpdateDocument',
            ai__model_dot_v1_dot_ai__model__pb2.UpdateDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/DeleteDocument',
            ai__model_dot_v1_dot_ai__model__pb2.DeleteDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/ListDocuments',
            ai__model_dot_v1_dot_ai__model__pb2.ListDocumentsRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/SearchDocuments',
            ai__model_dot_v1_dot_ai__model__pb2.SearchDocumentsRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.SearchDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StageDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/StageDocument',
            ai__model_dot_v1_dot_ai__model__pb2.StageDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/ActivateDocument',
            ai__model_dot_v1_dot_ai__model__pb2.ActivateDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/ArchiveDocument',
            ai__model_dot_v1_dot_ai__model__pb2.ArchiveDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/RollbackDocument',
            ai__model_dot_v1_dot_ai__model__pb2.RollbackDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.RAGDocument.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/ExtractDocument',
            ai__model_dot_v1_dot_ai__model__pb2.ExtractDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.ExtractDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExtractionJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/GetExtractionJob',
            ai__model_dot_v1_dot_ai__model__pb2.GetExtractionJobRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.ExtractionJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExtractionProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/StreamExtractionProgress',
            ai__model_dot_v1_dot_ai__model__pb2.StreamExtractionProgressRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.ExtractionProgressEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChunkDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/ChunkDocument',
            ai__model_dot_v1_dot_ai__model__pb2.ChunkDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.ChunkDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/ListChunks',
            ai__model_dot_v1_dot_ai__model__pb2.ListChunksRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.ListChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/GetChunk',
            ai__model_dot_v1_dot_ai__model__pb2.GetChunkRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.RagChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/DeleteChunks',
            ai__model_dot_v1_dot_ai__model__pb2.DeleteChunksRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.DeleteChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorizeDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/VectorizeDocument',
            ai__model_dot_v1_dot_ai__model__pb2.VectorizeDocumentRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.VectorizeDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVectorizationJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/GetVectorizationJob',
            ai__model_dot_v1_dot_ai__model__pb2.GetVectorizationJobRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.VectorizationJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmer_power.ai_model.v1.RAGDocumentService/QueryKnowledge',
            ai__model_dot_v1_dot_ai__model__pb2.QueryKnowledgeRequest.SerializeToString,
            ai__model_dot_v1_dot_ai__model__pb2.QueryKnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
