# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_model/v1/ai_model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_model/v1/ai_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61i_model/v1/ai_model.proto\x12\x18\x66\x61rmer_power.ai_model.v1\"\x81\x01\n\x11\x45xtractionRequest\x12\x13\n\x0braw_content\x18\x01 \x01(\t\x12\x13\n\x0b\x61i_agent_id\x18\x02 \x01(\t\x12\x1a\n\x12source_config_json\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x10\n\x08trace_id\x18\x05 \x01(\t\"\xa7\x01\n\x12\x45xtractionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1d\n\x15\x65xtracted_fields_json\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x19\n\x11validation_passed\x18\x04 \x01(\x08\x12\x1b\n\x13validation_warnings\x18\x05 \x03(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t\"\x14\n\x12HealthCheckRequest\"7\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\xe2\x01\n\x0e\x41iModelService\x12\x64\n\x07\x45xtract\x12+.farmer_power.ai_model.v1.ExtractionRequest\x1a,.farmer_power.ai_model.v1.ExtractionResponse\x12j\n\x0bHealthCheck\x12,.farmer_power.ai_model.v1.HealthCheckRequest\x1a-.farmer_power.ai_model.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_model.v1.ai_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTRACTIONREQUEST']._serialized_start=57
  _globals['_EXTRACTIONREQUEST']._serialized_end=186
  _globals['_EXTRACTIONRESPONSE']._serialized_start=189
  _globals['_EXTRACTIONRESPONSE']._serialized_end=356
  _globals['_HEALTHCHECKREQUEST']._serialized_start=358
  _globals['_HEALTHCHECKREQUEST']._serialized_end=378
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=380
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=435
  _globals['_AIMODELSERVICE']._serialized_start=438
  _globals['_AIMODELSERVICE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
