"""Kenya-specific data providers for Polyfactory generators.

This module provides Kenya-realistic data generation including:
- Kenyan first and last names (AC #3)
- Valid phone formats +254 7XX XXX XXX (AC #3)
- Kenya GPS bounds with altitude bands (AC #3)

Story 0.8.3: Polyfactory Generator Framework
AC #3: Kenya-specific data - Swahili names, +254 phone prefix, Kenya GPS bounds
"""

from __future__ import annotations

import random
from typing import ClassVar


class KenyaProvider:
    """Provider for Kenya-specific realistic data.

    All data generated by this provider is within valid ranges for Kenya:
    - Phone numbers use +254 prefix with valid operator codes
    - GPS coordinates are within Kenya bounds
    - Names are common Kenyan names
    """

    # Common Kenyan first names (male and female)
    FIRST_NAMES: ClassVar[list[str]] = [
        # Male names
        "James",
        "Daniel",
        "John",
        "Peter",
        "David",
        "Michael",
        "Joseph",
        "Samuel",
        "Stephen",
        "George",
        "Paul",
        "Mark",
        "Charles",
        "Patrick",
        "Francis",
        "Simon",
        "Martin",
        "Andrew",
        "Bernard",
        "Vincent",
        # Female names
        "Grace",
        "Sarah",
        "Mary",
        "Jane",
        "Ann",
        "Ruth",
        "Esther",
        "Faith",
        "Joyce",
        "Alice",
        "Beatrice",
        "Caroline",
        "Dorothy",
        "Elizabeth",
        "Florence",
        "Hannah",
        "Irene",
        "Janet",
        "Lucy",
        "Margaret",
    ]

    # Common Kenyan last names (tribal and regional mix)
    LAST_NAMES: ClassVar[list[str]] = [
        # Kalenjin
        "Kiprop",
        "Cheruiyot",
        "Bett",
        "Kosgei",
        "Langat",
        "Kipkemoi",
        "Kiptoo",
        "Chepkemoi",
        "Rotich",
        "Chirchir",
        # Kikuyu
        "Maina",
        "Kamau",
        "Njoroge",
        "Wanjiku",
        "Ngugi",
        "Kariuki",
        "Mbugua",
        "Gitau",
        "Macharia",
        "Muriithi",
        # Luo
        "Otieno",
        "Ochieng",
        "Odhiambo",
        "Owino",
        "Achieng",
        "Onyango",
        "Omondi",
        "Odongo",
        "Okoth",
        "Anyango",
        # Other common names
        "Nyambura",
        "Wambui",
        "Wairimu",
        "Njeri",
        "Wangui",
        "Mwangi",
        "Kimani",
        "Kinyua",
        "Mutua",
        "Musyoka",
    ]

    # Kenya phone operator prefixes (after +254)
    # Safaricom: 7XX (most common), Airtel: 7XX, Telkom: 77X
    PHONE_PREFIXES: ClassVar[list[str]] = [
        "70",  # Safaricom
        "71",  # Safaricom
        "72",  # Safaricom
        "79",  # Safaricom
        "74",  # Safaricom
        "75",  # Airtel
        "78",  # Airtel
        "77",  # Telkom/Orange
    ]

    # Kenya GPS bounds
    # Latitude: -4.7 to 4.6 (South to North)
    # Longitude: 33.9 to 41.9 (West to East)
    LATITUDE_MIN: float = -4.7
    LATITUDE_MAX: float = 4.6
    LONGITUDE_MIN: float = 33.9
    LONGITUDE_MAX: float = 41.9

    # Tea-growing highland regions (more specific bounds)
    # These are centered around the major tea-producing counties
    TEA_REGIONS: ClassVar[list[dict]] = [
        # Nyeri County (Central Kenya highlands)
        {
            "lat_min": -0.6,
            "lat_max": -0.2,
            "lng_min": 36.7,
            "lng_max": 37.2,
            "alt_min": 1400,
            "alt_max": 2200,
            "county": "nyeri",
        },
        # Kericho County (Rift Valley tea belt)
        {
            "lat_min": -0.6,
            "lat_max": -0.2,
            "lng_min": 35.0,
            "lng_max": 35.5,
            "alt_min": 1800,
            "alt_max": 2200,
            "county": "kericho",
        },
        # Nandi County (Western highlands)
        {
            "lat_min": 0.0,
            "lat_max": 0.4,
            "lng_min": 34.9,
            "lng_max": 35.3,
            "alt_min": 1600,
            "alt_max": 2100,
            "county": "nandi",
        },
        # Bomet County (South Rift)
        {
            "lat_min": -0.9,
            "lat_max": -0.6,
            "lng_min": 35.1,
            "lng_max": 35.5,
            "alt_min": 1600,
            "alt_max": 2000,
            "county": "bomet",
        },
        # Murang'a County (Central Kenya)
        {
            "lat_min": -0.9,
            "lat_max": -0.6,
            "lng_min": 36.8,
            "lng_max": 37.1,
            "alt_min": 1400,
            "alt_max": 2000,
            "county": "muranga",
        },
    ]

    # Altitude bands per project-context.md
    # Low: <800m, Medium: 800-1200m, High: >1200m
    ALTITUDE_BANDS: ClassVar[dict[str, tuple[int, int]]] = {
        "lowland": (0, 800),
        "midland": (800, 1200),
        "highland": (1200, 2500),
    }

    @classmethod
    def first_name(cls) -> str:
        """Generate a random Kenyan first name."""
        return random.choice(cls.FIRST_NAMES)

    @classmethod
    def last_name(cls) -> str:
        """Generate a random Kenyan last name."""
        return random.choice(cls.LAST_NAMES)

    @classmethod
    def phone_number(cls) -> str:
        """Generate a valid Kenya phone number.

        Format: +254 7XX XXX XXX
        Returns formatted string with +254 prefix.
        """
        prefix = random.choice(cls.PHONE_PREFIXES)
        # Generate remaining 7 digits (prefix is 2 digits, need 7 more for 9 total)
        remaining = "".join([str(random.randint(0, 9)) for _ in range(7)])
        return f"+254{prefix}{remaining}"

    @classmethod
    def kenya_coordinates(cls, tea_region: bool = True) -> tuple[float, float, float]:
        """Generate valid Kenya GPS coordinates with altitude.

        Args:
            tea_region: If True, generate coordinates in tea-growing highlands.
                       If False, generate anywhere in Kenya.

        Returns:
            Tuple of (latitude, longitude, altitude_meters).
        """
        if tea_region:
            # Pick a random tea-growing region
            region = random.choice(cls.TEA_REGIONS)
            lat = round(random.uniform(region["lat_min"], region["lat_max"]), 6)
            lng = round(random.uniform(region["lng_min"], region["lng_max"]), 6)
            # Altitude within the region's typical range
            alt = round(random.uniform(region["alt_min"], region["alt_max"]), 1)
        else:
            # Anywhere in Kenya
            lat = round(random.uniform(cls.LATITUDE_MIN, cls.LATITUDE_MAX), 6)
            lng = round(random.uniform(cls.LONGITUDE_MIN, cls.LONGITUDE_MAX), 6)
            # Random altitude (sea level to highlands)
            alt = round(random.uniform(0, 2500), 1)

        return lat, lng, alt

    @classmethod
    def kenya_coordinates_for_altitude_band(
        cls,
        altitude_band: str,
    ) -> tuple[float, float, float]:
        """Generate coordinates for a specific altitude band.

        Args:
            altitude_band: One of 'lowland', 'midland', or 'highland'.

        Returns:
            Tuple of (latitude, longitude, altitude_meters).
        """
        alt_min, alt_max = cls.ALTITUDE_BANDS.get(altitude_band, (800, 1400))
        alt = round(random.uniform(alt_min, alt_max), 1)

        # Use tea region bounds for lat/lng (reasonable approximation)
        region = random.choice(cls.TEA_REGIONS)
        lat = round(random.uniform(region["lat_min"], region["lat_max"]), 6)
        lng = round(random.uniform(region["lng_min"], region["lng_max"]), 6)

        return lat, lng, alt

    @classmethod
    def tea_region_county(cls) -> str:
        """Get a random tea-growing county name."""
        region = random.choice(cls.TEA_REGIONS)
        return region["county"]

    @classmethod
    def national_id(cls) -> str:
        """Generate a realistic Kenya national ID number.

        Kenya national IDs are 8 digits (older format) or alphanumeric.
        We generate 8-digit format for simplicity.
        """
        return "".join([str(random.randint(0, 9)) for _ in range(8)])

    @classmethod
    def grower_number(cls) -> str:
        """Generate a grower number in typical KTDA format.

        Format: GN-XXXXX (5 digits)
        """
        digits = "".join([str(random.randint(0, 9)) for _ in range(5)])
        return f"GN-{digits}"
